# Generated by Django 4.2.7 on 2024-09-10 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retefuente', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('correo', models.EmailField(max_length=256)),
                ('contrasena', models.CharField(max_length=256)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios')),
                ('rol', models.PositiveIntegerField(choices=[(1, 'Administrador'), (2, 'Colaborador')], default=2)),
                ('cargo', models.PositiveIntegerField(blank=True, choices=[(1, 'Almacenista'), (2, 'Analista de ingeniería'), (3, 'Aprendiz etapa lectiva'), (4, 'Aprendiz etapa práctica'), (5, 'Auditor(a)'), (6, 'Auxiliar contable'), (7, 'Auxiliar de almacén'), (8, 'Auxiliar de bodega'), (9, 'Auxiliar de calidad'), (10, 'Auxiliar de diseño'), (11, 'Auxiliar de gestión humana'), (12, 'Auxiliar de ingeniería'), (13, 'Auxiliar de mecánica'), (14, 'Auxiliar de servicios generales'), (15, 'Coordinador(a) de área'), (16, 'Despachador'), (17, 'Diseñador(a)'), (18, 'Domiciliario(a)'), (19, 'Gerente'), (20, 'Jefe de calidad'), (21, 'Jefe de compras'), (22, 'Jefe de despachos'), (23, 'Jefe de Gestión Humana'), (24, 'Jefe de planta'), (25, 'Mecánico(a)'), (26, 'Operario(a) de corte'), (27, 'Operario(a) de empaque'), (28, 'Operario(a) de extendido'), (29, 'Operario(a) de máquina'), (30, 'Operario(a) de máquinas especiales'), (31, 'Operario(a) de muestras'), (32, 'Operario(a) de terminación'), (33, 'Operario(a) manual'), (34, 'Patinador(a)'), (35, 'Patronista'), (36, 'Recepcionista'), (37, 'Revisor(a)'), (38, 'Secretario(a)'), (39, 'Supervisor(a)'), (40, 'Vigilante')], default=1, null=True)),
                ('salario', models.IntegerField()),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('riesgo', models.FloatField(blank=True, default=0, null=True)),
                ('tipo_contrato', models.PositiveIntegerField(blank=True, choices=[(1, 'Término fijo inferior a 1 año'), (2, 'Término fijo superior a 1 año'), (3, 'Contrato por obra y labor'), (4, 'Contrato indefinido')], null=True)),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('motivo_retiro', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_incapacidad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('dias_trabajados', models.PositiveIntegerField()),
                ('horas_extras_diurnas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('horas_extras_diurnas_dom_fes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('horas_extras_nocturnas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('horas_extras_nocturnas_dom_fes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('horas_recargo_nocturno', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('horas_recargo_nocturno_dom_fes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('horas_recargo_diurno_dom_fes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comisiones', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comisiones_porcentaje', models.FloatField(blank=True, default=0, null=True)),
                ('bonificaciones', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('embargos_judiciales', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('libranzas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cooperativas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('otros', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('usuario', models.ForeignKey(limit_choices_to={'fecha_retiro__isnull': True, 'rol': 2}, on_delete=django.db.models.deletion.CASCADE, to='nomina.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.deduccion')),
                ('devengado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.devengado')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.novedad')),
            ],
        ),
        migrations.AddField(
            model_name='devengado',
            name='novedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.novedad'),
        ),
        migrations.AddField(
            model_name='deduccion',
            name='devengado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.devengado'),
        ),
        migrations.AddField(
            model_name='deduccion',
            name='novedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.novedad'),
        ),
    ]
