# Generated by Django 5.0.6 on 2024-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('correo', models.EmailField(max_length=256)),
                ('contrasena', models.CharField(max_length=256)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios')),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Colaborador')], default=2)),
            ],
        ),
    ]
