# Generated by Django 4.2.7 on 2024-09-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='salario',
            field=models.IntegerField(default=100000),
        ),
    ]
