# Generated by Django 4.2.3 on 2024-08-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_remove_novedad_fecha_ingreso_usuario_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='clase_salario',
        ),
    ]
