# Generated by Django 4.2.7 on 2024-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_usuario_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default='Administrador', max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_contrato',
            field=models.CharField(default='Contrato indefinido', max_length=256),
        ),
    ]
