# Generated by Django 5.1 on 2024-08-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_remove_novedad_fecha_fin_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'fecha_retiro__isnull': True, 'rol': 2}, on_delete=django.db.models.deletion.CASCADE, to='nomina.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Almacenista'), (2, 'Analista de ingeniería'), (3, 'Aprendiz etapa lectiva'), (4, 'Aprendiz etapa práctica'), (5, 'Auditor(a)'), (6, 'Auxiliar contable'), (7, 'Auxiliar de almacén'), (8, 'Auxiliar de bodega'), (9, 'Auxiliar de calidad'), (10, 'Auxiliar de diseño'), (11, 'Auxiliar de gestión humana'), (12, 'Auxiliar de ingeniería'), (13, 'Auxiliar de mecánica'), (14, 'Auxiliar de servicios generales'), (15, 'Coordinador(a) de área'), (16, 'Despachador'), (17, 'Diseñador(a)'), (18, 'Domiciliario(a)'), (19, 'Gerente'), (20, 'Jefe de calidad'), (21, 'Jefe de compras'), (22, 'Jefe de despachos'), (23, 'Jefe de Gestión Humana'), (24, 'Jefe de planta'), (25, 'Mecánico(a)'), (26, 'Operario(a) de corte'), (27, 'Operario(a) de empaque'), (28, 'Operario(a) de extendido'), (29, 'Operario(a) de máquina'), (30, 'Operario(a) de máquinas especiales'), (31, 'Operario(a) de muestras'), (32, 'Operario(a) de terminación'), (33, 'Operario(a) manual'), (34, 'Patinador(a)'), (35, 'Patronista'), (36, 'Recepcionista'), (37, 'Revisor(a)'), (38, 'Secretario(a)'), (39, 'Supervisor(a)'), (40, 'Vigilante')], default=1, null=True),
        ),
    ]
