# Generated by Django 4.2.7 on 2024-09-10 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_alter_usuario_cargo_alter_usuario_tipo_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='novedad',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='novedad',
            name='fecha_novedad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
