# Generated by Django 5.0.6 on 2024-06-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_usuario_cedula_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='dias_incapacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='horas_extras_diurnas_dom_fes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='horas_extras_nocturnas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='horas_extras_nocturnas_dom_fes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='horas_recargo_diurno_dom_fes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='horas_recargo_nocturno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='horas_recargo_nocturno_dom_fes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
