# Generated by Django 4.2.7 on 2024-09-12 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_nomina_fecha_nomina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='fecha_novedad',
        ),
        migrations.AlterField(
            model_name='novedad',
            name='fecha_ultima_actualizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
