# Generated by Django 4.2.7 on 2024-09-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_remove_novedad_fecha_novedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='perm_no_remunerado',
            field=models.CharField(blank=True, default='No aplica', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='perm_remunerado',
            field=models.CharField(blank=True, default='No aplica', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='sin_justa_causa',
            field=models.CharField(blank=True, default='No aplica', max_length=256, null=True),
        ),
    ]
