# Generated by Django 4.2.7 on 2024-09-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_novedad_perm_no_remunerado_novedad_perm_remunerado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduccion',
            name='retefuente',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
