# Generated by Django 5.0.6 on 2024-06-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_remove_novedad_riesgo_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.novedad')),
            ],
        ),
    ]
