# Generated by Django 4.2.7 on 2024-09-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_alter_deduccion_retefuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduccion',
            name='retefuente',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
