# Generated by Django 5.0.6 on 2024-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_devengado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='comisiones_porcentaje',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
