# Generated by Django 4.2.3 on 2024-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0010_alter_deduccion_retefuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='incapacidad_porcentaje',
            field=models.FloatField(default=0.6666),
        ),
    ]
