# Generated by Django 5.1.2 on 2024-10-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_novedad_incapacidad_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='dias_trabajados',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
