# Generated by Django 5.0.6 on 2024-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_alter_novedad_comisiones_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='comisiones_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
