# Generated by Django 5.0.6 on 2024-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0012_alter_novedad_comisiones_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='comisiones_porcentaje',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
