# Generated by Django 4.2.3 on 2024-11-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0014_alter_novedad_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='creado_por',
        ),
    ]
