# Generated by Django 5.0.6 on 2024-06-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0014_alter_novedad_comisiones_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retefuente', models.CharField(max_length=256)),
                ('devengado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.devengado')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.novedad')),
            ],
        ),
    ]
