# Generated by Django 5.0.6 on 2024-06-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0015_deduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('deduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.deduccion')),
                ('devengado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.devengado')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.novedad')),
            ],
        ),
    ]
