# Generated by Django 4.2.3 on 2024-11-05 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0015_remove_novedad_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creados_por', to='nomina.usuario'),
        ),
    ]
