# Generated by Django 5.0.6 on 2024-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0017_alter_novedad_bonificaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='salario',
            field=models.FloatField(),
        ),
    ]
