# Generated by Django 4.2.3 on 2024-11-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0017_alter_usuario_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'fecha_retiro__isnull': True, 'rol': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creados_por', to='nomina.usuario'),
        ),
    ]
