# Generated by Django 5.0.6 on 2024-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0018_alter_novedad_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='comisiones_porcentaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
