# Generated by Django 5.0.6 on 2024-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0019_alter_novedad_comisiones_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='salario',
            field=models.IntegerField(),
        ),
    ]
