# Generated by Django 5.0.6 on 2024-06-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0021_remove_nomina_fecha_fin_remove_nomina_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaQuincena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nomina', models.ManyToManyField(to='nomina.nomina')),
            ],
        ),
    ]
