# Generated by Django 5.0.6 on 2024-06-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0023_alter_novedad_fecha_fin_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'rol': 2}, on_delete=django.db.models.deletion.CASCADE, to='nomina.usuario'),
        ),
    ]
