# Generated by Django 5.0.6 on 2024-06-17 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0024_alter_novedad_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='fecha_novedad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
