# Generated by Django 5.0.6 on 2024-06-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0025_novedad_fecha_novedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
